Services:
  WalletApiv1Url:
    settings-key: WalletApiV1Url
  WalletApiv2Url:
    settings-key: WalletApiV2Url
  CandlesHistoryServiceUrl:
    settings-key: CandlesHistoryServiceUrl
  SessionServiceUrl:
    settings-key: SessionServiceUrl
  AssetsServiceUrl:
    settings-key: AssetsServiceUrl
  BalancesServiceUrl:
    settings-key: BalancesServiceUrl
  ClientAccountServiceUrl:
    settings-key: ClientAccountServiceUrl
  RateCalculatorServiceUrl:
    settings-key: RateCalculatorServiceUrl
  TradesAdapterServiceUrl:
    settings-key: TradesAdapterServiceUrl
  RegistrationServiceUrl:
    settings-key: RegistrationServiceUrl
WalletApi:
  Secret:
    settings-key: AntaresWalletApi-WalletApi-Secret

MyNoSqlServer:
  ReaderServiceUrl:
    settings-key: MyNoSqlServer-ReaderUrl
  WriterServiceUrl:
    settings-key: MyNoSqlServer-WriterUrl
  PricesTableName:
    settings-key: MyNoSqlServer-PricesTableName
  CandlesTableName:
    settings-key: MyNoSqlServer-CandlesTableName
  TickersTableName:
    settings-key: MyNoSqlServer-TickersTableName
  OrderbooksTableName:
    settings-key: MyNoSqlServer-OrderbooksTableName
  PublicTradesTableName:
    settings-key: MyNoSqlServer-PublicTradesTableName
  SessionsTableName:
    settings-key: MyNoSqlServer-SessionsTableName
RabbitMq:
  Candles:
    ConnectionString:
      settings-key: CandlesConnectionString
    ExchangeName:
      settings-key: CandlesExchangeName
  PublicTrades:
    ConnectionString:
      settings-key: RabbitSpotPricesConnString
    ExchangeName:
      settings-key: PublicTradesExchangeName
MatchingEngine:
  Host:
    settings-key: MatchingEngine-Host
  Port:
    settings-key: MatchingEngine-Port
Redis:
  RedisConfiguration:
    settings-key: HFT-RedisConfiguration
  InstanceName:
    settings-key: OrderBooks-CacheInstance
  OrderBooksCacheKeyPattern:
    settings-key: OrderBooks-CacheKeyPattern
ElasticsearchLogs:
  NodeUrls:
    settings-key: ElasticSearch-NodeUrls
    types: [JsonArray]
  IndexPrefixName:
    settings-key: ElasticSearch-IndexPrefixName
Serilog:
  minimumLevel:
    default:
      settings-key: AntaresWallet-Serilog-DefaultMinLevel
    override:
      settings-key: AntaresWallet-Serilog-Override
      types: [Json]
